export enum TOKEN_INJECTION {
  COMPARE_HASH_PROVIDER = 'COMPARE_HASH_PROVIDER',
  HASH_PROVIDER = 'HASH_PROVIDER',
  DB_CREATE_USER = 'DB_CREATE_USER',
  DB_DELETE_USER = 'DB_DELETE_USER',
  DB_LIST_ALL_USERS = 'DB_LIST_ALL_USERS',
  DB_UPDATE_USER = 'DB_UPDATE_USER',
  ID_GENERATOR = 'ID_GENERATOR',
}
